name: Deploy Strapi to ECS (Blue/Green)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Strapi
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      ECS_CLUSTER: strapi-blue-green-cluster
      ECS_SERVICE: strapi-service
      TASK_FAMILY: strapi-task
      CONTAINER_NAME: strapi
      IMAGE_URI: baddamharika/strapi-app:latest
      DEPLOYMENT_GROUP: StrapiDeploymentGroup
      APPLICATION_NAME: StrapiCodeDeployApp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Substitute variables in taskdef
        run: |
         envsubst < taskdef.json > taskdef.temp.json
      - name: Validate taskdef JSON
        run: |
          jq . taskdef.temp.json


      - name: Register new ECS task definition
        id: register
        run: |
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://taskdef.temp.json \
            --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment-group `
          --application-name strapi-codedeploy-app `
          --deployment-group-name strapi-deploy-group `
          --service-role-arn arn:aws:iam::607700977843:role/CodeDeployECSRole `
          --deployment-config-name CodeDeployDefault.ECSAllAtOnce `
          --deployment-style deploymentType=BLUE_GREEN,deploymentOption=WITH_TRAFFIC_CONTROL `
          --blue-green-deployment-configuration "{"terminateBlueInstancesOnDeploymentSuccess":{"action":"TERMINATE","terminationWaitTimeInMinutes":5}}" ` --load-balancer-info "{"targetGroupPairInfoList":[{"targetGroups":[{"name":"strapi-target-group-bhr"}],"prodTrafficRoute":{"listenerArns"":["arn:aws:elasticloadbalancing:us-east-2:607700977843:listener/app/app-alb-strapi-bhr/0b6fa7f3d06532e7/7ddf1a1917450e0b"]}}]}" ` --ecs-services serviceName=strapi-service,clusterName=strapi-cluster-bhr

