name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy with CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name strapi-codedeploy-app \
          --deployment-group-name strapi-deployment-group \
          --description "Strapi Blue/Green Deployment" \
          --revision revisionType=AppSpecContent,s3Location={bucket=your-s3-bucket,key=appspec.yaml,bundleType=YAML} \
          --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes